# Basic Information 
title: Zhengxiong Luo
position: full-time researcher
affiliation: ByteDance Seed
email: lzxlog@qq.com

# Search Engine Optimization (SEO)
keywords: Zhengxiong Luo, computer vision, multimodal generation, video generation, super resolution, human pose estimation, deep learning
description: Zhengxiong Luo is a full-time researcher at ByteDance Seed, working on multimodal generation and understanding, video generation, and low-level vision.
canonical: https://greatlog.github.io/

# Links 
google_scholar: https://scholar.google.com.hk/citations?user=Sz1yTZsAAAAJ&hl=zh-CN
github_link: https://github.com/greatlog

# Google Scholar Citation Stats
google_scholar_stats_use_cdn: true
google_scholar_stats_cdn_url: https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fgreatlog%2Fgreatlog.github.io%40google-scholar-stats%2Fgs_data_shieldsio.json

# Images
avatar: ./assets/img/lzx.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Sans Serif"

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
  - google_scholar_crawler/
